# Generated by Django 4.1.5 on 2023-01-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.championmastery')),
            ],
        ),
    ]
