# Generated by Django 4.1.5 on 2023-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_word_champion_word_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championmastery',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
