# Generated by Django 4.1.5 on 2023-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_championmastery_id_alter_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
