# Generated by Django 4.1.5 on 2023-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
