# Generated by Django 4.1.5 on 2023-01-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_word_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='champion',
        ),
        migrations.AddField(
            model_name='word',
            name='champion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.championmastery'),
            preserve_default=False,
        ),
    ]
