# Generated by Django 4.1.5 on 2023-01-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='champion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.champion'),
            preserve_default=False,
        ),
    ]
