# Generated by Django 4.1.5 on 2023-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_champion_reason_champion_valid_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('valid', models.BooleanField()),
                ('reason', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
